[general]
#import = [
#    "~/.config/alacritty/themes/themes/monokai_pro.toml"
#]

[cursor]
blink_interval = 700
[cursor.style]
shape = "Block"
blinking = "Always"

[colors.primary]
background = '#000000'

[window]
opacity = 0.92
padding.x = 25
padding.y = 25

[font]
size = 18.0

[font.normal]
family = "Terminus"
style = "Regular"

[font.bold]
family = "Terminus"
style = "Bold"

[font.bold_italic]
family = "Terminus"
style = "Bold Italic"

[font.italic]
family = "Terminus"
style = "Italic"
