[general]
#import = [
#    "~/.config/alacritty/themes/themes/monokai_pro.toml"
#]

[colors.primary]
background = '#000000'

[window]
opacity = 0.92
padding.x = 10
padding.y = 10

[font]
size = 22.0

[font.normal]
family = "Terminus"
style = "Regular"

[font.bold]
family = "Terminus"
style = "Bold"

[font.bold_italic]
family = "Terminus"
style = "Bold Italic"

[font.italic]
family = "Terminus"
style = "Italic"
