[general]
import = [
    "~/.config/alacritty/themes/themes/monokai_pro.toml"
]

[window]
opacity = 0.92
padding.x = 10
padding.y = 10

[font]
size = 16.0

[font.normal]
family = "Terminus"
style = "Normal"

[font.bold]
family = "Terminus"
style = "Heavy"

[font.bold_italic]
family = "Terminus"
style = "Heavy Italic"

[font.italic]
family = "Terminus"
style = "Medium Italic"
